version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - fast_box-network

  db:
    image: 'postgres:14.0-alpine'
    restart: unless-stopped
    env_file:
      - ./docker/db/env.env
    ports:
      - "5437:5432"
    networks:
      - fast_box-network
    volumes:
      - postgres:/var/lib/postgresql/data


networks:
  fast_box-network:

volumes:
  postgres: